### ISSUE TITLE
Gradient not working properly

### ISSUE THREAD

**Issue by ImNotStable** [Oli-idk/EasyMC#147] opened 2024-03-27 03:10 UTC
![image](https://github.com/birdflop/web/assets/51060503/aeebcbdd-afb2-45ec-9678-27e9876a6580)

**Comment by saboooor** [comment] 2024-03-28 03:04
Please explain how you came across this problem, so that we can try to recreate it

**Comment by bwmp** [comment] 2024-03-28 06:36
![image](https://github.com/birdflop/web/assets/67001116/a87c74e4-254f-4870-adea-9235dca01fef)
using those exact colors im getting the proper output.
What is the browser you are using?

**Comment by ImNotStable** [comment] 2024-03-29 05:19
Sorry, I just saw these replies, I'm using Brave browser. I originally was using the default Color Preset, I then changed it to my desired gradient, any changes after that left any color I attempted to input being incorrect.

**Comment by ImNotStable** [comment] 2024-03-29 05:19
I also copied and pasted the hex codes without #'s I then added them if that helps.

**Comment by ImNotStable** [comment] 2024-03-29 05:20
I can't reproduce it though, originally it didn't work without #'s not sure how I caused that.

**Comment by ImNotStable** [comment] 2024-04-02 23:52
It happened again 
![image](https://github.com/birdflop/web/assets/51060503/20dd2e65-7d82-4df9-ac5f-941a95954d88)

**Comment by bwmp** [comment] 2024-04-02 23:53
do you know how to reproduce the bug?

**Comment by ImNotStable** [comment] 2024-04-02 23:54
I do not know exactly how to, but I can list what I did.

**Comment by ImNotStable** [comment] 2024-04-02 23:54
1. Open birdflop & https://www.digminecraft.com/lists/color_list_pc.php
2. Copy directly from the hex of a color code
3. The bug occurs

**Comment by bwmp** [comment] 2024-04-02 23:58
i cant seem to reproduct it if you can find a 100% way to reproduct how its done and list it out that will make it so we can test on our own and attempt to fix it

**Comment by ImNotStable** [comment] 2024-04-03 00:00
I can try, but I can't guarantee anything. I've had this happened twice so it will probably appear again.

**Comment by saboooor** [comment] 2024-06-15 09:46
Please re-open this issue if you find a way to reproduce it. There have been many changes since this issue has been posted and it quite possibly may have been fixed by itself

**Closed as completed by saboooor** 2024-06-15 09:46 UTC
